# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KDxFBXJjTWqLf_cJQ9KLRx3dTR8zZPCV
"""

import matplotlib.pyplot as plt
import numpy as np
import subprocess
import shlex
# Create the vectors X and Y
x = np.linspace(-10,10,300)
y = x ** 2 - 4*x + 6

# Create the plot
plt.plot(x,y,label='y = x**2-4x+6')

# Add a title
plt.title('')

# Add X and y Label
plt.xlabel('x axis')
plt.ylabel('y axis')

# Add a grid
plt.grid(alpha=1,linestyle='--')

# Add a Legend
plt.legend()
# Show the plot
plt.show()